### ISSUE TITLE
Curreny warning and modal takes long to pop up

### ISSUE THREAD

**Issue by the22mastermind** [Flutterwave/flutterwave-react-native#13]
**Issues**
1. I am getting the following warning when the component mounts:
`Warning: Failed prop type: Invalid prop `options.currency` of value `RWF` supplied to `PayWithFlutterwave`, expected one of ["GBP","NGN","USD","GHS","KES","ZAR","TZS"].
    in PayWithFlutterwave (at App.js:21)`

2. The modal takes long to pop up (about 6 seconds).
Is this the normal behaviour? I would prefer to have it pop up at the touch of button (1 second max), How could I achieve this?

**My code**
`
<PayWithFlutterwave
 onRedirect={handleRedirect}
 options={{
  tx_ref: 'unique_tx_ref',
  authorization: 'MY_PUBLIC_TEST_KEY',
  customer: {
   email: 'customer@domain.com',
   name: 'John David',
  },
  amount: 15000,
  currency: 'RWF',
  payment_options: 'mobilemoneyrwanda',
 }}
/>
`

**My dependencies**
`
"dependencies": {
    "flutterwave-react-native": "^1.0.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-webview": "^11.0.2"
  },
`

**Comment by Corvus97** [comment]
Hello @the22mastermind ,

Thank you for bringing this to our attention.

Kindly be informed that the team has deployed a bug fix to address the issue raised. Please update your npm package and retry the charge.

Regards,
Cornelius from Flutterwave

**Comment by the22mastermind** [comment]
Hi @Corvus97 ,

Thank you for the prompt response. I updated the package and  everything is working okay now.
