### ISSUE TITLE
Flutterwave payment  webview  screen does not close when close button is pressed

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [Flutterwave/flutterwave-react-native#17]
I have been trying to process flutter-wave transaction in react native using  PayWithFlutterWave component in flutterwave-react-native.However,after the OTP verification step, and entering my momo pin,I wanted to close the Flutterwave payment modal by tapping on the close button at the top right corner of the flutterwave  payment screen. Tapping the close button does not close the modal. It show the attached image.
Kindly assist me to fix.
![Screenshot_20210208_141946_com telehealth](https://user-images.githubusercontent.com/43665909/107232370-3cb2a780-6a19-11eb-9989-ee8f72a7c554.jpg)

**Comment by thecodecafe** [comment]
Hi @Akola-Mbey-Denis, there appears to be no button on the top right corner of the page, can you share a state in which the button on the top right shows? Also, are you saying that when you tap on the close button it loads nonstop as shown on your attached image?

**Comment by Akola-Mbey-Denis** [comment]
Thanks,I increase the view height of the web view and I was able to close the button.

**Comment by thecodecafe** [comment]
All right @Akola-Mbey-Denis will be closing this now, but feel free to reopen anytime you experience this again.
