### ISSUE TITLE
Redirect callback on payment cancellation

### ISSUE THREAD

**Issue by gems-inc** [Flutterwave/flutterwave-react-native#20]
How do I get rid of the heroku-app redirect callback when I cancel my payment. I try fixing with the "onAbort" method but still will not work
![Screenshot_20210315-152704](https://user-images.githubusercontent.com/79230501/111169320-2319f800-85a3-11eb-800d-b5d7f194b030.png)

**Comment by thecodecafe** [comment]
Hell @gems-inc, unfortunately, on Android the default title for an alert called in a WebView is the URL of the page that was loaded in the WebView. The checkout page is loaded in a WebView, and the "Cancel Payment" button triggers an alert on that page, and we don't have control over the content of the title.
Although we're still looking for a workaround, there's no solution to this at the moment, I'll be closing this issue, for now. Thanks.
