### ISSUE TITLE
Changig currency option to GHS and payment _options to Card,does display card payment webview. I keep seeing Mobile MOney webview screen

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [Flutterwave/flutterwave-react-native#21]
I have another issue now,when I change the payment options to Card and currency to GHS, I expect to be presented with web view for card payment,but it still  shows a web view for mobile money payment. Kindly help to fix out.

**Comment by thecodecafe** [comment]
Hi @Akola-Mbey-Denis, I just tried and the only time mobile money with GHS was forced was when I enabled dashboard payment options from the dashboard app from the Account tab in settings.
Please log into the dashboard at http://dashboard.flutterwave.com and navigate to Settings > Account Settings and scroll to the `Enable Dashboard Payment Options` setting and if it is selected make sure you have card payments enabled or you uncheck it so you can determine the payment options from within your code, please let me know if this solves your problem.

**Comment by Akola-Mbey-Denis** [comment]
Thank you.It is working fine now.

**Comment by thecodecafe** [comment]
Great, I'll be closing this issue now, feel free to reopen if this comes up again in the future.
