### ISSUE TITLE
val.replace is not a function

### ISSUE THREAD

**Issue by danielolamide** [Flutterwave/flutterwave-react-native#22]
This error pops up when using `payment_method : 'mpesa'` and the pay button is clicked.
<img width="319" alt="Screenshot 2021-04-22 at 17 59 27" src="https://user-images.githubusercontent.com/29626957/115741896-d511c480-a398-11eb-9faa-33a39eaca74e.png">

**Comment by thecodecafe** [comment]
Hello, @danielolamide are you still experiencing this?

**Comment by danielolamide** [comment]
I haven't given it a shot since I posted this issue. Let me try it out.

**Comment by danielolamide** [comment]
@thecodecafe It's still an issue I'm using test credentials

**Comment by danielolamide** [comment]
@thecodecafe any update on what the issue could be?

**Comment by thecodecafe** [comment]
Hello @danielolamide this is being looked into, will have feedback for you as soon as I can.

**Comment by thecodecafe** [comment]
Hi @danielolamide this seems to work fine on my end right now, can you try again? If you get the same error, please share your implementation, remember to remove your keys.

**Comment by danielolamide** [comment]
I've not gotten that error. Now it says the payment is currently not available. **NB: I've updated the required documentation for my account**

**Comment by Pelps12** [comment]
I also got this issue when using the test cards

**Comment by iykeprince** [comment]
I am currently getting this error and  i am using a test card, what could be causing it? and solution?
Thanks

**Comment by Pelps12** [comment]
Check the body of your transaction it may be incomplete but flutterwave doesn’t mark it as required. For example, I forgot to add the payment options field

**Comment by thecodecafe** [comment]
Hi, we'll do well to make sure proper checks are done for the properties on the individual fields on the PayWithFlutterwave component, normally you would see a prop-types warning message when calling the component if you didn't pass a required field, if you do not see the message please [use this table as a guide](https://github.com/Flutterwave/flutterwave-react-native#flutterwaveinitoptions) to know what fields are required and what fields are not.
I'll be closing this for now but feel free to re-open with a comment if the solution given here does not work for you.
Happy coding! 🤝

**Comment by the-fanan** [comment]
Getting this response when passing metadata
