### ISSUE TITLE
Problem enabling bank transfer

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [Flutterwave/flutterwave-react-native#23]
Hello team,
I have being trying to activate bank transfer payment options  for sometime now But,I am not able to see that options as a part of my payment methods.
 I tried activating that option using **payment_options: 'banktransfer**' in react native PayWithFlutterwave component,but it has worked out. Kindly help to resolve this for me.
Thanks,

**Comment by thecodecafe** [comment]
Hello, @Akola-Mbey-Denis seems to be the same problem with [this issue](https://github.com/Flutterwave/flutterwave-react-native/issues/21#issuecomment-800035654), you will need to go into your dashboard and uncheck dashboard payment options if you want to determine payment options from payment initialisation.
Please let me know if this solves your problem.
Thanks.

**Comment by thecodecafe** [comment]
Hello @Akola-Mbey-Denis, I'll be closing this, for now, feel free to reopen it if the proposed solution above does not suffice.
