### ISSUE TITLE
PayWithFlutterwave does not work with expo

### ISSUE THREAD

**Issue by jacquesikot** [Flutterwave/flutterwave-react-native#25]
I'm trying to use this module on a react native expo managed workflow app and it doesn't seem to be working. The button is rendered properly, but when it is pressed, it blurs for a while, in some loading state but doesn't open the webview, after a few seconds it returns to normal and nothing happens, no errors or response.

**Comment by thecodecafe** [comment]
Hello @jacquesikot apologies for the delayed response, please can you confirm you already had [react-native-webview](https://www.npmjs.com/package/react-native-webview) installed? Also, can you share your implementation(remove your public key)?

**Comment by phoward38** [comment]
The package worked previously for me, but now the modal opens & shows `invalid link`

**Comment by thecodecafe** [comment]
Hi @phoward38 all right, this is being looked into, will feedback here as I receive updates.

**Comment by thecodecafe** [comment]
Hi @phoward38 this issue you mentioned has been resolved please try again.
