### ISSUE TITLE
Could you provide a working sample code that archives what's displayed on the gif?

### ISSUE THREAD

**Issue by BtMwanza** [Flutterwave/flutterwave-react-native#32]
I have looked at this repository for weeks and I still can't make the payment work due to some missing parts of the code, like the `handleOnRedirect` function. It would be easier if a working code sample is provided.

**Comment by thecodecafe** [comment]
Hi @BtMwanza, sorry to hear you're having a hard time with the docs, we'll definitely work on improving it.

To display a payment button you can use the following.
[https://github.com/Flutterwave/flutterwave-react-native#paywithflutterwave](https://github.com/Flutterwave/flutterwave-react-native#paywithflutterwave)

Here's an example of what the `handleOnRedirect` function will receive.
[https://github.com/Flutterwave/flutterwave-react-native#redirectparams](https://github.com/Flutterwave/flutterwave-react-native#redirectparams)

Hope this helps point you in the right direction.

Also, feel free to share your pain points with the docs, you can let me know what you tried, your expectations, and the unwanted results.

Please let me know if this worked for you.

Thanks.
