### ISSUE TITLE
Payment does not initialize for some phones in production mode

### ISSUE THREAD

**Issue by Obhenimen** [Flutterwave/flutterwave-react-native#34]
Thanks for this payment platform. 
The payment failed to initialize on Royale lite 2, android version 7 with the app in production mode. I was able to make payment successfully with other phones. Except for the Royale lite 2

**Comment by thecodecafe** [comment]
Hi @Obhenimen, is this still an issue you're experiencing?

**Comment by thecodecafe** [comment]
@Obhenimen closing this due to in activity, feel free to open again if this ever comes up.
