### ISSUE TITLE
Issues using test cards in Flutterwave React native package

### ISSUE THREAD

**Issue by Akola-Mbey-Denis** [Flutterwave/flutterwave-react-native#35]
Please I can try to test flutter wave payment in my mobile app. However,I am unable to do so since I am not using a payment link with the flutter wave-react-native package. I would be grateful if you could help me out.
Sincerely,
Denis Mbey Akola

**Comment by thecodecafe** [comment]
Hi @Akola-Mbey-Denis, can you help confirm the following:
1. You are using test cards from the Flutterwave developer documentation. [https://developer.flutterwave.com/docs/test-cards](https://developer.flutterwave.com/docs/test-cards)?
2. Your account is in test mode while you are running the test?
3. You are using the test public key from your account?
Let me know if you've met all these criteria for testing, thanks.
