### ISSUE TITLE
the cancel payement button seems not to work well when you try to close the webview modal 

### ISSUE THREAD

**Issue by frank505** [Flutterwave/flutterwave-react-native#5]
I noticed that once i click the cancel payement text at the bottom of the modal  it doesnt close the modal , rather it freezes the modal and nothing on the modal works including the input fields sometimes if i click the cancel button it closes the app too, although i must say that i only noticed this behaviour on IOS

**Comment by thecodecafe** [comment]
Thanks, @frank505 will test this to see what's causing this behaviour.

**Comment by thecodecafe** [comment]
Reopended

**Comment by frank505** [comment]
**" Although will need to know, does tapping on the cancel button display an alert asking you to confirm the action?"** on android yes it does but on IOS it doesnt, it just closes the app

**Comment by kenny-io** [comment]
@thecodecafe

**Comment by thecodecafe** [comment]
Hi @frank505, I have not been able to reproduce this behaviour can, you share your implementation or an example repo I can test with? I have tried on several simulators(iPhone 8, 11, and 11 Pro) and they all worked correctly. Sharing your code/implementation will be helpful, thanks!

**Comment by frank505** [comment]
i will do just this once i get back home, create a new repo and use my implementation , thanks so much i appreciate :)

**Comment by frank505** [comment]
here is my implementation :


```
import {PayWithFlutterwave} from 'flutterwave-react-native'
import {REACT_FLUTTERWAVE_KEY} from '../../../../ApiKeys'

  <PayWithFlutterwave
           onRedirect={JoinStream}
          options={{
         tx_ref: ""+Math.random()+""+(new Date().getTime()),
        authorization: REACT_FLUTTERWAVE_KEY,
        customer: {
         email: loggedInUserEmail
         },
        amount: parseInt("10"),
       currency: 'NGN',
       payment_options: 'card'
       }}    
      customButton={(props) => (
    <TouchableOpacity
      style={styles.btnCustom}
      onPress={props.onPress}
      isBusy={props.isInitializing}
      disabled={props.disabled}>
        <Text style={styles.paymentButtonText}>Join Stream</Text>
    </TouchableOpacity>
  )}
/>
```

**Comment by thecodecafe** [comment]
Seen @frank505 will test this and revert as soon as I can with a solution.

**Comment by frank505** [comment]
would appreciate :) thanks

**Comment by thecodecafe** [comment]
Hi @frank505 I can't seem to replicate this behaviour, what device(and model) are you testing on?

**Comment by frank505** [comment]
i am testing on an IOS simulator running xcode 11.6 and an iphone 7 too...although i thought of creating a brand new project and adding only flutterwave as the dependency then building for IOS to see if i still see the same behaviour, if i dont then it may be something breaking the app when i hit the close button

**Comment by thecodecafe** [comment]
Hi @frank505, did the fresh React Native project behave the same way?

**Comment by frank505** [comment]
oh boi! should have closed this issue, i simply reinstalled all my dependencies and it worked. :) thanks
