### ISSUE TITLE
onRedirect is required but not specified on the readme

### ISSUE THREAD

**Issue by dammyson** [Flutterwave/flutterwave-react-native#6]
<PayWithFlutterwave
        onComplete={this.onSuccess()}
        onRedirect={(params)=>this.onRedirect(params)}
    
      />

**Comment by thecodecafe** [comment]
Hi @dammyson, thanks for pointing that out, we've made the necessary adjustments to the docs to reflect the required `onRedirect` prop, you also don't need the `onComplete` prop anymore that has been removed in favour of `onRedirect`.
I Will be closing this issue now as it's been resolved, thanks!
