### ISSUE TITLE
Does this work with expo ?

### ISSUE THREAD

**Issue by Abdoulrasheed** [Flutterwave/flutterwave-react-native#9]
How do I go about the [Activity Indicator ](https://github.com/Flutterwave/flutterwave-react-native#activity-indicator-only-needed-for-android) config section without ejecting from expo ?

**Comment by thecodecafe** [comment]
@Abdoulrasheed will test but I think GIF works out of the box for Expo.

**Comment by thecodecafe** [comment]
Hi @Abdoulrasheed please I've been quite occupied and lost track of this, can you confirm if you've been able to resolve this?

**Comment by Abdoulrasheed** [comment]
I couldn't use the library but I was able to integrate and receive payments via webview.
